### ISSUE TITLE
Expose error_code / alarm

### ISSUE THREAD

**Issue by N3rdix** [suaveolent/hoymiles-wifi#10]
**Is your feature request related to a problem? Please describe.**
It can happen that the inverter does not work properly, e.g. after a power outage. I had this several times and the DTU reported an error in the S-Miles installer app.

**Describe the solution you'd like**
It would be nice to see at least that there is an error reported. Ideally we could extract the error text as well, but a boolean would help as well.

**Describe alternatives you've considered**
Tried to dig into the protobuf stuff and debugged the requests, but could not find why the error_code listed there is not returned (maybe if it's zero at the time of request?)

**Comment by suaveolent** [comment]
@N3rdix I implemented the `get-alarm-list` command in the `main` branch. However, I cannot yet see any errors. Maybe you can try it out?

**Comment by N3rdix** [comment]
> @N3rdix I implemented the `get-alarm-list` command in the `main` branch. However, I cannot yet see any errors. Maybe you can try it out?

That's great news, I will give it a try the next days. An AC disconnect should be enough to provoke an error, at least that's what I observed when the circuit breaker tripped

**Comment by N3rdix** [comment]
Just disconnected AC and gave it a try, but it seems I do not get a response while an alarm was visible in the Homiles App.
Other functions return data in the response, just to rule out a general issue.

```
DTU Response: dtu_sn: "414393319405"
time: 1718523928
action: 50
tid: 1718523923
```

That's my sample script:
```
from hoymiles_wifi.dtu import DTU
import asyncio

dtu = DTU("xx.xx.xx.xx")
   
async def main():
    response = await dtu.async_get_alarm_list()
    if response:
        print(f"DTU Response Alarm: {response}")
    else:
        print("Unable to get Alarm response!")

asyncio.run(main())
```
