### ISSUE TITLE
Question: writing to EEPROM or volatile memory?

### ISSUE THREAD

**Issue by Boulder08** [suaveolent/hoymiles-wifi#11]
Thank you for the project, I'm planning on installing a Hoymiles based system and this will be very useful for collecting data to a database and administering the system in general.

Do you know if the values like the power limit set via wifi are written to the EEPROM or the volatile memory? It seems to be an issue with Home Assistant where the power limit setting is written to EEPROM which kills it quite fast.

**Comment by suaveolent** [comment]
Unfortunately it seems to write to EEPROM. 

See https://github.com/suaveolent/ha-hoymiles-wifi/issues/16#issuecomment-2028690822
