### ISSUE TITLE
Inverter Support: Hoymiles HMT-2250-6T

### ISSUE THREAD

**Issue by Sonnenwerk** [suaveolent/hoymiles-wifi#16]
I have a Hoymiles HMT-2250-6T Inverter. It is not in the list of "valid" inverters.
Can you please add it too ?

**Comment by suaveolent** [comment]
Sure thing, please post the first 4 digits of the serial number for the inverter.

**Comment by Sonnenwerk** [comment]
That is an easy one :-)
 1382

**Comment by Sonnenwerk** [comment]
Haha - not as easy as i thought..it was serial of the DTU..
4130 is the serial of the inverter

**Comment by suaveolent** [comment]
Thanks, that's the one I was looking for.
