### ISSUE TITLE
Error output as json with commands identify-dtu and identify-inverters

### ISSUE THREAD

**Issue by pipp37** [suaveolent/hoymiles-wifi#19]
**Thanks**
First thanks for great tool. 
I made a docker container and found a issue on 2 commands with json output.

**Describe the bug**
Output as json generates some errors with hms800w-2t and DTUL. 
Normal output runs fine with Response: 

Coommands: 
- identify-dtu 
- identify-inverters

**To Reproduce**
1. RUN: hoymiles-wifi --host 192.168.28.193  identify-inverters - OK
2. RUN: hoymiles-wifi --host 192.168.28.193  identify-inverters --as-json  - ERROR
3. See error

**Expected behavior**
Output should generate json string

**Screenshots**
look at attached logfile.

**Linux :**
 - OS: debian-bullseye - docker AMD64
 - Microinverter HM800w-2t at 192.168.28.193
 - Docker container: https://hub.docker.com/r/pipp37/hoymiles-wifi-python/tags
 - CMD:  docker run -it --rm pipp37/hoymiles-wifi-python:1.0 bash
 - hoymiles-wifi --host 192.168.28.193  identify-dtu --as-json  (Error)
 - hoymiles-wifi --host 192.168.28.193  identify-dtu  (OK)
 - Version hoymiles-wifi: 0.2.2

[bash-shell-log-error.txt](https://github.com/user-attachments/files/15971123/bash-shell-log-error.txt)

**Comment by pipp37** [comment]
Docker python container: python:3.12.4-slim-bullseye

**Comment by suaveolent** [comment]
Thanks I somehow missed this issue: will have a look at it.
