### ISSUE TITLE
PV-Data as Json Output

### ISSUE THREAD

**Issue by Maddogtet** [suaveolent/hoymiles-wifi#2]
Hey thanks for your good work!

Would be nice to have a command where it is possible to get the result as a json parseble array. 
Is this possible to implement?

With kind regards

**Comment by suaveolent** [comment]
Sure should be easy enough to implement. Will have a look at it.

**Comment by marcelK0** [comment]
haha, yes I had the same thing and spent quite some time yesterday to figure out how to parse the current output ;)

**Comment by suaveolent** [comment]
Just to make sure: you are using the main.py (cli invocation) and not the library itself right? 

So a parameter, such as —as-json would work for you?

**Comment by suaveolent** [comment]
@Maddogtet @marcelK0 should be fixed with `v0.1.2` now.
