### ISSUE TITLE
No power data as soon as internet connection is lost

### ISSUE THREAD

**Issue by m0w1337** [suaveolent/hoymiles-wifi#22]
**Describe the bug**
As soon as the inverter cannot communicate with s-miles cloud, the python script will not return production data when issuing the command get-real-data-new.

**To Reproduce**
Prevent the inverter from communicating to the s-miles cloud.

**Expected behavior**
It would be good, if values are available without cloud connection. That was the mail reason to move towards a local API, to prevent communication to any cloud. Did anybody try this before? I think the problem is, that the inverter disconnects from wifi as soon as it looses cloud connection. Is there any way getting around this issue?

UPDATE: I found out, that data can actually be received as long as the inverter is connected to wifi. The only problem is, the inverter is reconnecting every fiew minutes leaving the data reception with big gaps.

**Comment by kumy** [comment]
@m0w1337 do you have any news?
