### ISSUE TITLE
Two WLAN-Devices and two HMS-800W-2T on one Raspi #27 

### ISSUE THREAD

**Issue by Jo-Bl** [suaveolent/hoymiles-wifi#28]
Thanks.

But sorry, this doesn't work. Independent from the setting at "--local_addr" it requests server every time on wlan1 (10.10.100.151 -> 10.10.100.254) but sadly never wlan0 (10.10.100.150 -> 10.10.100.254)

Not working (wlan0, requests wlan1 instead):
./hoymiles-wifi --host 10.10.100.254 --local_addr 10.10.100.150 --as-json get-real-data-new

working (wlan1);
./hoymiles-wifi --host 10.10.100.254 --local_addr 10.10.100.151 --as-json get-real-data-new

_Originally posted by @Jo-Bl in https://github.com/suaveolent/hoymiles-wifi/issues/27#issuecomment-2345712890_

**Comment by suaveolent** [comment]
Thanks for the feedback. That is weird indeed.

What about if you enter a non existend interface, e.g. 10.10.100.149? To you still get a response?

**Comment by Jo-Bl** [comment]
I'm only seeing your answer now, sorry.

I'm now using the two HMS-800W-2Ts with two Rasps.

But I was able to test it with only wlan0 and eth0 interfaces, if I remember correctly: Then no data query is possible with an incorrect IP. But if wlan0 and wlan1 are present, then a query with an incorrect IP is possible. As I said: I can't test that at the moment because I'm now working with two Rasps. Sorry.

**Comment by suaveolent** [comment]
Thanks for letting me know.

by the way: you can also connect the inverter directly to your WiFi router. So you can query both inverters with one raspberry too.

**Comment by Jo-Bl** [comment]
You wrote:
> you can also connect the inverter directly to your WiFi router

Aha, how? 

I do not found an option about that connecting to my router in the android app "S-Miles Installer" 

- I do not want any cloud between/around me and the inverters.
- And - second - the inverters are never allowed to go online themselves.
- The connection of Hoymiles(-support, - updater) to the inverters must remain prevented

Is this possible than, if the interters are connected to the router?

**Comment by suaveolent** [comment]
You can set the wifi network of the inverter via the `set-wifi` command. This allows you to connect the inverter to your main wifi. Then you can use the IP address from the main router to query your inverters as before.

To prevent the inverter from communicating with hoymiles servers you need to create a firewall rule in your router.
I have set up my inverter this way.

The only issue which arises from this setup is that the inverter sometimes is not reachable (presumably due to it trying to connect to the Hoymiles server at this time). 

Also bear in mind: There might be some wifi stability issues if you have never update the firmware up until now (I'm working on an offline approach to do so, but it does not work as of this moment).

**Comment by Jo-Bl** [comment]
> You can set the wifi network of the inverter via the `set-wifi` command. 
I know that (thanks for implement this), but I don't want it.
 
Reasons:
> To prevent the inverter from communicating with hoymiles servers you need to create a firewall rule in your router.
> 
> The only issue which arises from this setup is that the inverter sometimes is not reachable (presumably due to it trying to connect to the Hoymiles server at this time).
> 
> There might be some wifi stability issues if you have never update the firmware up until now 

So I preferr AP mode and will stay on this mode for both inverters.

> (I'm working on an offline approach to do so, but it does not work as of this moment).
Thanks for this!

**Comment by suaveolent** [comment]
I see makes sense :)

There are two reasons for the disconnects: 

1. old firmware is buggy. You need to update to the latest firmware to improve WiFi stability 
2. Offline mode, as described above.

**Comment by Jo-Bl** [comment]
2024-09-15T12:48:29|get-real-data-new|No response or unable to retrieve response for get-real-data-new
2024-09-15T12:49:23|get-real-data-new|{"deviceSerialNumber":.... 2024-09-15T12:50:11|get-real-data-new|{"deviceSerialNumber":... 2024-09-15T12:50:58|get-real-data-new|{"deviceSerialNumber":....
2024-09-15T12:51:45|get-real-data-new|No response or unable to retrieve response for get-real-data-new
2024-09-15T12:52:37|get-real-data-new|{"deviceSerialNumber":...
2024-09-15T12:53:25|get-real-data-new|{"deviceSerialNumber":...

**Comment by suaveolent** [comment]
> 2024-09-15T12:48:29|get-real-data-new|No response or unable to retrieve response for get-real-data-new 2024-09-15T12:49:23|get-real-data-new|{"deviceSerialNumber":.... 2024-09-15T12:50:11|get-real-data-new|{"deviceSerialNumber":... 2024-09-15T12:50:58|get-real-data-new|{"deviceSerialNumber":.... 2024-09-15T12:51:45|get-real-data-new|No response or unable to retrieve response for get-real-data-new 2024-09-15T12:52:37|get-real-data-new|{"deviceSerialNumber":... 2024-09-15T12:53:25|get-real-data-new|{"deviceSerialNumber":...

That looks a lot like the output I would expect if run in offline mode. So in the end it probably doesn’t really matter if you use AP mode or offline mode.

**Comment by Jo-Bl** [comment]
Yes.

**Comment by suaveolent** [comment]
Yes, I’m still investigating. Will probably run some tests on a rpi tomorrow.

**Comment by Jo-Bl** [comment]
Thank you

**Comment by suaveolent** [comment]
@Jo-Bl I begin to wonder whether this is an OS/underlying library issue.

When i was using `eth0` and `wlan0` I could switch between the interfaces using `local_addr` just fine. I also verified it setting special firewall rules in my router.

However, as soon as I also connected my Edimax USB adapter and set up `wlan1` it would only allow connections via `wlan1`. When I tried to use the local_addr for `eth0` or `wlan0` I would not get any response. 

According to the documentation, the use of `local_addr`, however, should be exactly what you are looking for.

**Comment by suaveolent** [comment]
I am also seeing a lot of these errors, when the edimax is connected:

https://github.com/raspberrypi/linux/issues/6049

**Comment by Jo-Bl** [comment]
> @Jo-Bl I begin to wonder whether this is an OS/underlying library issue.
> 
> When i was using `eth0` and `wlan0` I could switch between the interfaces using `local_addr` just fine. I also verified it setting special firewall rules in my router.
> 
> However, as soon as I also connected my Edimax USB adapter and set up `wlan1` it would only allow connections via `wlan1`. When I tried to use the local_addr for `eth0` or `wlan0` I would not get any response.
> 
> According to the documentation, the use of `local_addr`, however, should be exactly what you are looking for.

Sorry for not describing the behavior better (I was more interested in the data than in testing and trying it out): It is exactly as you describe and have tested it.

**Comment by suaveolent** [comment]
Right, I forgot to paste the link to the documentation:

https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection

**Comment by Jo-Bl** [comment]
> I am also seeing a lot of these errors, when the edimax is connected:
> 
> [raspberrypi/linux#6049](https://github.com/raspberrypi/linux/issues/6049)

But it is possible to connect to two different (hoymiles-)APs with wlan0 and wlan1, only to sepatate them via IP does not work. Is there another way to do that? Via 'wlan0' and 'wlan1' or so?

**Comment by suaveolent** [comment]
Yes, it might be possible by directly creating a socket. However, this approach will only work for Linux based systems. The IP-based approach should look up the interface independed of the OS and select the appropriate interface automatically.

I can try to push an update today with this approach to see if it works. 

By the way, just to make sure: I assume you set the IP-adddress manually right?  Because the hoymiles begins setting the IP at 10.10.100.150. So if you have two different devices, both of them would try to assign the client the 10.10.100.150 IP.

**Comment by Jo-Bl** [comment]
First I let it be assigned automatically and that worked very well. (I got .150 from the first inverter and .151 from the second inverter).

When fetching on two interfaces didn't work and you then implemented --local_addr, I also tried with static IPs.

**Comment by Jo-Bl** [comment]
The IP-based approach should look up the interface independet of the OS and select the appropriate interface automatically.

Yes, this is like e.g. a linux app 'wol' do to select the interface, to send the magic packet.

On the oher hand ssh selects the interface according the routing table?
