### ISSUE TITLE
Mismatch in version 

### ISSUE THREAD

**Issue by Sonnenwerk** [suaveolent/hoymiles-wifi#31]
Hi,
i have those informations available.

software version of Hoymiles integration
<img width="240" alt="image" src="https://github.com/user-attachments/assets/07e0fdfc-359d-48ec-a753-99139696ff18">

DTUBI aka HMS800W
<img width="263" alt="image" src="https://github.com/user-attachments/assets/bac68526-27ab-41bd-9d2b-6f93d66ff6b5">

DTU aka Lite-S
<img width="247" alt="image" src="https://github.com/user-attachments/assets/5cd68a60-34a0-488b-a572-699623ab33f1">

Looks like the Lite-S did not update correctly, or is this a mismatch with the software versioning ?

btw my HMS still works (after update), but my HMT does not display any data no more. Not sure, what i can provide that you could have a look into the issue

**Comment by suaveolent** [comment]
Thanks. 

the version looks fine to me. The SW version is the version of the DTU/inverter. Not the integration. 

Regarding the missing data from HMT: can you look into the logs if there is anything? 

Otherwise you can try to reconfigure the integration by clicking on the three vertical dots next to the DTU. 

Just make sure that the DTU and inverter is available.

**Comment by Sonnenwerk** [comment]
Hi,
i had a look into the data the HMT 2250 delivers and marked my suggestions. 
Regarding the "Zählermodel" - it seems to be not a SW Version, nor the Gridprofile. It seems to be something different, that is not shown in the hoymiles cloud.

device_serial_number: "4ddd"
timestamp: 172dfafaf
active_power: 1
firmware_version: 1
tgs_data {
  serial_number: dddd
  firmware_version: 1
  
  
  **active_power: 7243** --> most important information is not shown in HA
  current_phase_A: 105 --> would be nice to have it shown too
  current_phase_B: 105 --> would be nice to have it shown too
  current_phase_C: 105 --> would be nice to have it shown too
  power_factor: 1000 --> would be nice to have it shown too
  temperature: 246
  warning_number: 1
  link_status: 1
  modulation_index_signal: -82
}


}
pv_data {
  serial_number:dd
  port_number: 3
  voltage: 433
  current: 294
  power: 1276
  energy_total: 273140
  energy_daily: 153
  **error_code: 50986752** --> i guess this is a "no error"-code. It would be nice to have it also in the entities available, as it shows on the panel level if there is an error.

**Comment by suaveolent** [comment]
Thanks, I should be able to integrate them for three-phase inverters.

**Comment by suaveolent** [comment]
@Sonnenwerk all of the values should be added now with `v0.3.1`.

**Comment by Sonnenwerk** [comment]
I installed and checked the new version. 
The error code and active power works.
The fields for phase current are shown, but contain no value im HA
The daily energy still does not work. It should come from DTU, but it shows 0. 

<img width="359" alt="image" src="https://github.com/user-attachments/assets/ab4e4da7-4f97-474a-825a-8db121d215ff">
<img width="499" alt="image" src="https://github.com/user-attachments/assets/5abc4c3e-c580-4b5c-b7b0-00002a3218dd">
