### ISSUE TITLE
Unknown inverter type: 0x14 0x10

### ISSUE THREAD

**Issue by Toutatis64** [suaveolent/hoymiles-wifi#33]
**Describe the bug**
I've a configuration with an inverter with 2 ports, but with one deactivated because no solar panel on it.
Probably why i've this specific inverter type ? This is not managed by the hoymiles-wifi today, and i miss one inverter in the list :(

Here are the logs

Logger: hoymiles_wifi
Source: custom_components/hoymiles_wifi/entity.py:58
integration: Hoymiles ([documentation](https://github.com/suaveolent/ha-hoymiles-wifi), [issues](https://github.com/suaveolent/ha-hoymiles-wifi/issues))
First occurred: October 30, 2024 at 7:59:51 PM (440 occurrences)
Last logged: 9:27:48 AM

Unknown inverter type: 0x14 0x10

**** 
Should consider the type of  0x14 0x10 as  InverterType.ONE, and if unknown, should have an InverterType.UNKNOWN to let the other fields be completed ?

**Comment by suaveolent** [comment]
Can you tell me your inverter name/model so I can add it?

**Comment by Toutatis64** [comment]
My inverter is  HMS-1000

**Comment by suaveolent** [comment]
Thanks, should be an easy fix. I will push a new version this weekend.

**Comment by Toutatis64** [comment]
Thanks a lot !
