### ISSUE TITLE
Update frequency workaround

### ISSUE THREAD

**Issue by philiip11** [suaveolent/hoymiles-wifi#4]
I've noticed that after a restart, the limitation to two updates per minute is not enforced until sunset.

So if you want to fetch the current power every second, just call `inverter.restart()` once after sunrise.
For the rest of the day, the restriction is lifted.

**Comment by suaveolent** [comment]
Thanks that is indeed a nice find. 
I will evaluate that, but probably needs to be implemented in the home assistant custom component rather than the lib.

**Comment by henk23** [comment]
Hi @philiip11 Thanks for this finding. I can't seem to get it to work though.
Do you mean the `restart-dtu` command?
This command either does not work or does not lift the limitation...
