### ISSUE TITLE
JSON in Script

### ISSUE THREAD

**Issue by JonathanN1203** [suaveolent/hoymiles-wifi#6]
Hi,

Unfortunately I don't have the option to format the output as Json. How does this work?

My Current code:

```from hoymiles_wifi.dtu import DTU
import asyncio

dtu = DTU("10.12.11.102")
response = asyncio.run(dtu.async_get_real_data_hms())

if response:
    print(f"DTU Response: {response}")

```

**Comment by suaveolent** [comment]
The json option is only available from CLI. 

If you use the library itself, you need to parse the response as JSON yourself. 


See main.py for example how to do this.

**Comment by suaveolent** [comment]
@JonathanN1203 quick note: you should use the real data new function. 

The hms is deprecated and will be removed in the future.

**Comment by JonathanN1203** [comment]
to you mean the function `async_get_real_data` or `async_get_real_data_new`?

**Comment by suaveolent** [comment]
`async_get_real_data_new`

**Comment by JonathanN1203** [comment]
ok, will the name change in future?

**Comment by suaveolent** [comment]
> ok, will the name change in future?

No it will stay the same. This is the name taken directly from the Hoymiles app.

**Comment by JonathanN1203** [comment]
ok, perfect
