### ISSUE TITLE
 'HoymilesButtonEntity' object has no attribute '_inverter' 

### ISSUE THREAD

**Issue by Neukircher** [suaveolent/hoymiles-wifi#9]
Hallo, 
die button restart-dtu, turn-on-inverter and turn-off-inverter, gehen nach dem update nicht mehr. Bekomme die Fehlermeldung:  'HoymilesButtonEntity' object has no attribute '_inverter' 

Grüße

**Comment by suaveolent** [comment]
Thanks. 

I just pushed a new version which fixes the issue.

By the way: Issue should have been reported at: https://github.com/suaveolent/ha-hoymiles-wifi.
